### PR TITLE
Change navbar colours for table of contents.

### LINKED ISSUE #935: Update navigation colour to csfg-light
We should update the navigation colours to match #932 

image

### PR DESCRIPTION
**Pull request by courtneycb**
Updates the navigation bar colours for the table of contents to fit the csfg theme.

I made the hover colour on the nav links slightly darker than $csfg so there was a more noticable change in colour upon hovering over the link.

Resolves #935

### CODE REVIEW

**Comment by courtneycb** [comment]
> What do you think about also changing hyperlink colours? Here, appendices, `sections in this chapter`, links within chapter content and so forth. They now look kinda like ugly ducklings
> 
> image

Hmmm yeah it crossed my mind but I honestly don't know. I'll post in the technical channel to get some opinions?

**Comment by eAlasdair** [comment]
I've suggested a colour scheme for links based on the colours my browser/search engine uses. It fits in much better, though visited links might stand out too much. Not sure if we need a different colour for them

**Comment by eAlasdair** [comment]
On second thought I removed the visited links colour - it's not used in the current field guide nor here

**Comment by courtneycb** [comment]
Happy with your changes

**Pull request merged**
