### PR TITLE
URL redirects

### PR DESCRIPTION
**Pull request by courtneycb**
This PR redirects https://csfieldguide.org.nz/index.html to https://csfieldguide.org.nz/ and tidies some code in the `urls.py` files.

~~HELP WANTED:~~

- Currently the redirects for permalinks are incorrect. For example `/chapters/algorithms.html#searching` should redirect to `/chapters/algorithms/searching/` but instead it redirects to `http://localhost:81/en/chapters/algorithms/#searching`.

- Here are the two redirects I found that do not work:
In `chapters/urls.py`:
```
    # eg: redirect /chapters/algorithms.html#searching to /chapters/algorithms/searching/
    url(
        r"^(?P<chapter_slug>[-\w]+).html#(?P<chapter_section_slug>[-\w]+)$",
        RedirectView.as_view(permanent=True, pattern_name="chapters:chapter_section"),
    ),
```
In `curriculum_guides/urls.py`:
```
    # eg: redirect /curriculum-guides/apcsp/index.html#abstraction to /curriculum-guides/apcsp/abstraction/
    url(
        r"^(?P<curriculum_guide_slug>[-\w]+)/index.html#(?P<curriculum_guide_section_slug>[-\w]+)$",
        RedirectView.as_view(permanent=True,
                             pattern_name="curriculum_guides:curriculum_guide_section"),
    ),
```

I tried overriding the `get_url_redirect` method in `views.py` but the code would never get hit? Not sure what's going on and don't seem to be getting very far with it.

### CODE REVIEW

**Comment by eAlasdair** [comment]
Did some research. Anchor parameters (the bit after the #) do not get sent as part of the request, so the server never knows about them. Your code never got hit because those redirects never got hit. There is no way those redirects can do what they are attempting, so they can be removed.

**Comment by courtneycb** [comment]
> Did some research. Anchor parameters (the bit after the #) do not get sent as part of the request, so the server never knows about them. Your code never got hit because those redirects never got hit. There is no way those redirects can do what they are attempting, so they can be removed.

That's a pain. Thanks for doing that research. Should we re-word sentences so the user doesn't expect to be taken directly to the section?

**Comment by eAlasdair** [comment]
> > Did some research. Anchor parameters (the bit after the #) do not get sent as part of the request, so the server never knows about them. Your code never got hit because those redirects never got hit. There is no way those redirects can do what they are attempting, so they can be removed.
> 
> That's a pain. Thanks for doing that research. Should we re-word sentences so the user doesn't expect to be taken directly to the section?

Which sentences? Any current content will take the user directly to the section, because it uses the current style. It's just links to the old version can only link to the introduction page of the new version

**Comment by courtneycb** [comment]
> Which sentences? Any current content will take the user directly to the section, because it uses the current style. It's just links to the old version can only link to the introduction page of the new version

Oh man, ignore me. Confused about something else.

**Pull request merged**
