### PR TITLE
Credit the specific MIPS emulator linked to here

### PR DESCRIPTION
**Pull request by alanhogan**
Really cool to find out my MIPS assembler & emulator are featured in your textbook. I thought a specific credit would be appropriate.

### CODE REVIEW

**Comment by Heidirose** [comment]
Hi Alan,

Thanks for your suggestion, I'm guessing somebody should be able to approve this soon. We are working on property crediting all the resources we use, and will also mention you on the page we have dedicated for that.

Your emulator has allowed many NZ high school students to actually play around with a low level language. For that we really thank you :D

**Comment by JackMorganNZ** [comment]
Hi @alanhogan,

Thanks for your edit, we are very happy to credit you properly! 

I should mention that in our long term plan is to use our own version of a MIPS emulator, as we can directly control it's reliability. The emulator you provide is great, however if the webpage disappears in a few years, there isn't much we can do (this happens constantly with the amount of links in our guide). So we are trying to create our own versions of all the 'interactives' in the CSFG. I did see you share the source code on your website, is this available under any open source license?

**Comment by alanhogan** [comment]
@Heidirose I’m gratified that something as simple as keeping my work online has been able to give so many students zero set-up, universally available way to play with MIPS!

@JackMorganNZ Thanks for bringing this up! I hate linkrot and will continue to do what I can, barring excessive obstacles, to keep my tools and really everything else I have shared, online. I’m sorry you have seen so many other resources disappear. And I totally, 100% support your effort to host your own “interactives” in order to ensure all the important linked resources you provide continue to be available.

To that end, I want to apply an open source license to my assembler & simulator.

How does [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/) sound?

**Comment by alanhogan** [comment]
I threw the scripts up on GitHub an attached the aforementioned CC BY-NC-SA 4.0 license on them.

https://github.com/alanhogan/online-mips-assembler
https://github.com/alanhogan/miphps-mips-simulator

Think this will work for you? My understanding is that this is not a commercial endeavour and that you have no problem with attribution, so I think that license will work just fine.

**Comment by JackMorganNZ** [comment]
Thanks @alanhogan, that's perfect! You're correct with saying this is a non-commercial endeavor, our project is under the same CC BY-NC-SA 4.0 license.

I've added the MIPS assembler to the guide on branch `interactives/mips-assembler`. Would you be able to check you're happy with how we have used it? I'm hosting the [current version here](http://www.cosc.canterbury.ac.nz/csfieldguide/prototypes/mips-assembler/) for easier viewing.

We have added attribution within the footer of the interactive, and also in the README of the interactive folder and within the `included-files` document which is shown in the appendices online.

**Comment by alanhogan** [comment]
@JackMorganNZ Oops, somehow I didn’t see your comment until now. Email inbox fail :)

You moved fast! That’s great. Yeah, I’m very happy to see this. And your version looks a lot better than the awful styles I slapped on it so long ago, too.

You can always reach me at http://alanhogan.com/contact in the future.

**Pull request merged**
